import {
  Bell,
  Building2,
  LayoutDashboard,
  Package,
  Receipt,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Table2,
  Users,
  UtensilsCrossed,
} from "lucide-react";

export const GLOBAL_NAVIGATION_ITEMS = [
  {
    to: "/dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    permission: "analytics:read",
    keywords: ["home", "sales", "overview"],
  },
  {
    to: "/menu-engineering",
    label: "Menu Engineering",
    icon: Sparkles,
    permission: "analytics:read",
    keywords: ["margin", "profit", "items", "analytics"],
  },
  {
    to: "/orders",
    label: "Orders",
    icon: ShoppingBag,
    permission: "orders:read",
    keywords: ["order", "ticket", "sale"],
  },
  {
    to: "/menu",
    label: "Menu",
    icon: UtensilsCrossed,
    permission: "menu:read",
    keywords: ["item", "category", "modifier", "promotion"],
  },
  {
    to: "/availability",
    label: "Availability",
    icon: Bell,
    permission: "menu:read",
    keywords: ["stock", "schedule", "available"],
  },
  {
    to: "/tables",
    label: "Tables",
    icon: Table2,
    permission: "tables:read",
    keywords: ["table", "floor", "seating"],
  },
  {
    to: "/inventory",
    label: "Inventory",
    icon: Package,
    permission: "inventory:read",
    keywords: ["stock", "ingredient", "low stock"],
  },
  {
    to: "/staff",
    label: "Staff",
    icon: Users,
    permission: "staff:read",
    keywords: ["employee", "user", "role"],
  },
  {
    to: "/billing",
    label: "Billing",
    icon: Receipt,
    permission: "billing:read",
    keywords: ["plan", "subscription", "invoice"],
  },
  {
    to: "/business",
    label: "Business",
    icon: Building2,
    permission: "branch:read",
    keywords: ["organization", "franchise", "branch"],
  },
  {
    to: "/audit",
    label: "Audit Log",
    icon: ShieldCheck,
    permission: "audit:read",
    keywords: ["activity", "history", "changes"],
  },
  {
    to: "/settings",
    label: "Settings",
    icon: Settings,
    keywords: ["configuration", "preferences"],
  },
] as const;
