import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, ClipboardCheck, Route } from "lucide-react";
import { CtaBanner } from "@/components/marketing/CtaBanner";
export const metadata: Metadata = { title: "Restaurant Operations Resources", description: "Practical guides for evaluating connected restaurant operations." };
const resources = [
  [Route, "Connected operations checklist", "Map how an order moves between guest, waiter, kitchen, billing and reporting before evaluating software.", "/workflow"],
  [ClipboardCheck, "Implementation readiness", "Gather the branch, menu, tax, payment, staff, kitchen and device decisions needed for launch.", "/onboarding"],
  [BookOpen, "Product capability guide", "Review the Servora modules and focused applications that make up the current platform.", "/product"],
];
export default function ResourcesPage(){return <><section className="mx-auto max-w-7xl px-6 py-20 lg:px-8"><div className="max-w-4xl"><p className="text-sm font-semibold text-primary">Resources</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Evaluate the operation before choosing another isolated screen.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-text-secondary">Use these practical starting points to define your restaurant workflow and prepare a more useful product conversation.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{resources.map(([Icon,title,text,href])=>{const C=Icon as typeof Route;return <Link key={title as string} href={href as string} className="rounded-2xl border border-border bg-surface p-7 transition hover:-translate-y-0.5 hover:shadow-md"><C className="text-primary"/><h2 className="mt-5 text-xl font-semibold">{title as string}</h2><p className="mt-3 text-sm leading-6 text-text-secondary">{text as string}</p><span className="mt-5 inline-flex items-center text-sm font-semibold text-primary">Open resource <ArrowRight className="ml-1" size={15}/></span></Link>})}</div><section className="mt-16 rounded-3xl border border-border bg-surface-secondary p-8"><h2 className="text-2xl font-semibold">More useful content should follow real deployments.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-text-secondary">Implementation guides, operational benchmarks and customer case studies should be added when Servora has verified deployment evidence. This avoids publishing invented performance claims.</p></section></section><CtaBanner /></>}
