export const RESERVED_SYSTEM_ROLE_NAMES = [
  "OWNER",
  "FRANCHISE_ADMIN",
  "MANAGER",
  "CHEF",
  "WAITER",
  "CASHIER",
  "INVENTORY_MANAGER",
  "RECEPTIONIST",
  "ACCOUNTANT",
] as const;

export type SystemRoleName = (typeof RESERVED_SYSTEM_ROLE_NAMES)[number];

export const SYSTEM_ROLE_PERMISSIONS: Record<
  SystemRoleName,
  readonly string[]
> = {
  OWNER: [
    "analytics:read",
    "audit:read",
    "auth:read",
    "billing:create",
    "billing:read",
    "billing:refund",
    "branch:archive",
    "branch:create",
    "branch:read",
    "branch:update",
    "inventory:adjust",
    "inventory:create",
    "inventory:read",
    "inventory:update",
    "inventory:waste",
    "kitchen:read",
    "kitchen:update",
    "menu:create",
    "menu:delete",
    "menu:pricing:write",
    "menu:publish",
    "menu:read",
    "menu:update",
    "orders:cancel",
    "orders:comp",
    "orders:create",
    "orders:read",
    "orders:update",
    "orders:update_status",
    "orders:void",
    "organization:manage",
    "permissions:read",
    "roles:archive",
    "roles:assign_permissions",
    "roles:create",
    "roles:read",
    "roles:update",
    "settings:read",
    "settings:update",
    "staff:assign_branch",
    "staff:assign_role",
    "staff:create",
    "staff:deactivate",
    "staff:read",
    "staff:update",
    "tables:create",
    "tables:delete",
    "tables:read",
    "tables:update",
    "tenant:archive",
    "tenant:create",
    "tenant:manage_members",
    "tenant:read",
    "tenant:update",
  ],
  FRANCHISE_ADMIN: [
    "analytics:read",
    "audit:read",
    "billing:create",
    "billing:read",
    "billing:refund",
    "branch:archive",
    "branch:create",
    "branch:read",
    "branch:update",
    "inventory:adjust",
    "inventory:create",
    "inventory:read",
    "inventory:update",
    "inventory:waste",
    "kitchen:read",
    "kitchen:update",
    "menu:create",
    "menu:delete",
    "menu:pricing:write",
    "menu:publish",
    "menu:read",
    "menu:update",
    "orders:cancel",
    "orders:comp",
    "orders:create",
    "orders:read",
    "orders:update",
    "orders:update_status",
    "orders:void",
    "organization:manage",
    "permissions:read",
    "roles:archive",
    "roles:assign_permissions",
    "roles:create",
    "roles:read",
    "roles:update",
    "settings:read",
    "settings:update",
    "staff:assign_branch",
    "staff:assign_role",
    "staff:create",
    "staff:deactivate",
    "staff:read",
    "staff:update",
    "tables:create",
    "tables:delete",
    "tables:read",
    "tables:update",
    "tenant:archive",
    "tenant:manage_members",
    "tenant:read",
    "tenant:update",
  ],
  MANAGER: [
    "analytics:read",
    "audit:read",
    "billing:create",
    "billing:read",
    "branch:read",
    "branch:update",
    "inventory:adjust",
    "inventory:create",
    "inventory:read",
    "inventory:update",
    "inventory:waste",
    "kitchen:read",
    "kitchen:update",
    "menu:create",
    "menu:delete",
    "menu:pricing:write",
    "menu:publish",
    "menu:read",
    "menu:update",
    "orders:cancel",
    "orders:comp",
    "orders:create",
    "orders:read",
    "orders:update",
    "orders:update_status",
    "orders:void",
    "settings:read",
    "staff:create",
    "staff:read",
    "staff:update",
    "tables:create",
    "tables:delete",
    "tables:read",
    "tables:update",
  ],
  CHEF: ["kitchen:read", "kitchen:update", "menu:read", "orders:read"],
  WAITER: [
    "branch:read",
    "menu:read",
    "orders:create",
    "orders:read",
    "orders:update",
    "orders:update_status",
    "tables:read",
    "tables:update",
  ],
  CASHIER: [
    "billing:create",
    "billing:read",
    "billing:refund",
    "orders:read",
    "orders:update_status",
    "tables:read",
  ],
  INVENTORY_MANAGER: [
    "inventory:adjust",
    "inventory:create",
    "inventory:read",
    "inventory:update",
    "inventory:waste",
  ],
  RECEPTIONIST: ["menu:read", "orders:read", "tables:read", "tables:update"],
  ACCOUNTANT: ["analytics:read", "billing:read"],
};

export const isReservedSystemRoleName = (name: string): boolean =>
  (RESERVED_SYSTEM_ROLE_NAMES as readonly string[]).includes(
    name.trim().toUpperCase(),
  );
