import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { solutions } from "@/content/solutions";
import { CtaBanner } from "@/components/marketing/CtaBanner";

export const metadata: Metadata = { title: "Restaurant Solutions", description: "Explore Servora by restaurant role and operating model." };
const Group = ({ type, title, description }: { type: "role" | "business"; title: string; description: string }) => <section className="mt-16"><div className="max-w-2xl"><h2 className="text-3xl font-bold tracking-tight">{title}</h2><p className="mt-3 text-text-secondary">{description}</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{solutions.filter((item) => item.type === type).map((item) => <Link key={item.slug} href={`/solutions/${item.slug}`} className="group rounded-2xl border border-border bg-surface p-6 transition hover:-translate-y-0.5 hover:border-primary-border hover:shadow-md"><p className="text-sm font-semibold text-primary">{item.eyebrow}</p><h3 className="mt-3 text-xl font-semibold">{item.name}</h3><p className="mt-3 text-sm leading-6 text-text-secondary">{item.description}</p><span className="mt-5 inline-flex items-center text-sm font-semibold text-primary">Explore <ArrowRight className="ml-1" size={15} /></span></Link>)}</div></section>;
export default function SolutionsPage() { return <><section className="mx-auto max-w-7xl px-6 pb-20 pt-16 lg:px-8 lg:pt-24"><div className="max-w-4xl"><p className="text-sm font-semibold text-primary">Solutions</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">A connected platform, shaped around the way your restaurant works.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-text-secondary">Start with the team you want to help or the operating model you need to support.</p></div><Group type="role" title="For every restaurant role" description="Give each team a focused workspace while preserving one shared operational context." /><Group type="business" title="For different restaurant models" description="Use the same connected foundation across service styles without making claims beyond the workflows Servora currently supports." /></section><CtaBanner /></> }
