import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const h=vi.hoisted(()=>({branchId:"b1",stats:{} as any,orders:{} as any,margins:{} as any,refetchStats:vi.fn(),refetchOrders:vi.fn()}));
vi.mock("@/store/auth",()=>({useAuthStore:(sel:any)=>sel({branchId:h.branchId})}));
vi.mock("@/features/analytics/hooks/useDashboardRealtimeSync",()=>({useDashboardRealtimeSync:vi.fn()}));
vi.mock("@/features/analytics/hooks/useDashboardStats",()=>({useDashboardStats:()=>h.stats}));
vi.mock("@/features/orders/hooks/useOrders",()=>({useOrders:()=>h.orders}));
vi.mock("@/features/analytics/hooks/useCostMarginReport",()=>({useCostMarginReport:()=>h.margins}));
vi.mock("@tanstack/react-router",()=>({Link:({children,to,...p}:any)=><a href={String(to)} {...p}>{children}</a>}));
vi.mock("@pos/ui",()=>({
 Page:({children}:any)=><div>{children}</div>,PageHeader:({title,description,actions}:any)=><header><h1>{title}</h1><p>{description}</p>{actions}</header>,Grid:({children}:any)=><div>{children}</div>,Card:({children}:any)=><section>{children}</section>,StatCard:({title,value}:any)=><div><span>{title}</span><span>{value}</span></div>,StatusBadge:({label}:any)=><span>{label}</span>,Badge:({children,...p}:any)=><span {...p}>{children}</span>,Button:({children,...p}:any)=><button {...p}>{children}</button>,SkeletonCard:()=> <div>loading-card</div>
}));
import { DashboardPage } from "../DashboardPage";

describe("DashboardPage coverage",()=>{beforeEach(()=>{vi.clearAllMocks();h.branchId="b1";h.stats={data:undefined,isLoading:false,isError:false,refetch:h.refetchStats,isFetching:false};h.orders={data:[],isLoading:false,isError:false,refetch:h.refetchOrders};h.margins={data:[],isLoading:false};});
 it("covers loading, stats error, all-branch and active-order error states",()=>{h.branchId="all";h.stats={...h.stats,isLoading:true,isError:true,isFetching:false};h.orders={...h.orders,isError:true};const {rerender}=render(<DashboardPage/>);expect(screen.getAllByText("loading-card").length).toBeGreaterThan(0);fireEvent.click(screen.getByRole("button",{name:/^Retry$/}));expect(h.refetchStats).toHaveBeenCalled();h.stats={...h.stats,isLoading:false,isError:false,data:{totalOrdersToday:0,revenueToday:0,activeOrders:0,lowStockAlerts:0,averageOrderValue:0,paidOrdersToday:0,cancelledOrdersToday:0,topItems:[],revenueByHour:[]}};rerender(<DashboardPage/>);expect(screen.getByText("All branches")).toBeTruthy();expect(screen.getByText(/Select a branch/)).toBeTruthy();expect(screen.getByText(/Active orders could not be loaded/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Retry orders"}));expect(h.refetchOrders).toHaveBeenCalled();});
 it("covers populated selected-branch dashboard, margins, sorting/filtering and active orders",()=>{h.stats={...h.stats,data:{totalOrdersToday:12,revenueToday:1200,activeOrders:2,lowStockAlerts:1,averageOrderValue:100,paidOrdersToday:10,cancelledOrdersToday:1,topItems:[{name:"Latte",count:4,revenue:400}],revenueByHour:[{hour:9,revenue:0},{hour:10,revenue:500}]}};h.margins={isLoading:false,data:[{menuItemId:"i1",variantId:null,menuItemName:"Latte",variantName:null,categoryId:"c1",categoryName:"Drinks",price:100,cost:40,margin:60,marginPercent:60},{menuItemId:"i2",variantId:"v2",menuItemName:"Tea",variantName:"Large",categoryId:"c2",categoryName:"Tea",price:80,cost:null,margin:null,marginPercent:null},{menuItemId:"i3",variantId:null,menuItemName:"Toast",variantName:null,categoryId:"c1",categoryName:"Drinks",price:50,cost:40,margin:10,marginPercent:20}]};h.orders={...h.orders,data:Array.from({length:6},(_,i)=>({id:`order00000${i}`,status:i===0?"OPEN":"UNKNOWN",items:[{}],createdAt:new Date().toISOString(),totalAmount:100}))};render(<DashboardPage/>);expect(screen.getByText(/Operations need attention/)).toBeTruthy();expect(screen.getAllByText("Latte").length).toBeGreaterThan(0);expect(screen.getByText(/Cost not configured/)).toBeTruthy();expect(screen.getByText(/View all active orders/)).toBeTruthy();fireEvent.change(screen.getByLabelText("Filter margin report by category"),{target:{value:"c1"}});expect((screen.getByLabelText("Filter margin report by category") as HTMLSelectElement).value).toBe("c1");fireEvent.change(screen.getByLabelText("Sort margin report"),{target:{value:"low"}});expect(screen.getByText("Toast")).toBeTruthy();});
 it("covers margin loading and empty operational states",()=>{h.stats={...h.stats,data:{totalOrdersToday:1,revenueToday:1,activeOrders:0,lowStockAlerts:0,averageOrderValue:1,paidOrdersToday:1,cancelledOrdersToday:0,topItems:[],revenueByHour:[]}};h.margins={data:[],isLoading:true};const {rerender}=render(<DashboardPage/>);expect(screen.getByText("Operations look clear")).toBeTruthy();expect(screen.getByText("No active orders right now")).toBeTruthy();h.margins={data:[],isLoading:false};rerender(<DashboardPage/>);expect(screen.getByText("No menu items to report yet.")).toBeTruthy();});
});
