import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const m=vi.hoisted(()=>({save:vi.fn(),groups:[] as any[],tags:[] as any[],allergens:[] as any[],categories:[] as any[]}));
vi.mock("@/features/menu/hooks/useSaveMenuItem",()=>({useSaveMenuItem:()=>({isPending:false,mutate:m.save})}));
vi.mock("@/features/menu/hooks/useModifierGroups",()=>({useModifierGroups:()=>({data:m.groups})}));
vi.mock("@/features/menu/hooks/useMenuTags",()=>({useMenuTags:()=>({data:m.tags})}));
vi.mock("@/features/menu/hooks/useMenuAllergens",()=>({useMenuAllergens:()=>({data:m.allergens})}));
vi.mock("@/features/menu/hooks/useMenuCategories",()=>({useMenuCategories:()=>({data:m.categories})}));
vi.mock("@pos/ui",()=>({
 Button:({children,loading:_l,...p}:any)=><button {...p}>{children}</button>,
 Modal:({open,title,children}:any)=>open?<div role="dialog" aria-label={title}><h2>{title}</h2>{children}</div>:null,
 Input:React.forwardRef(({label,error,...p}:any,ref:any)=><label>{label}<input ref={ref} aria-label={label} {...p}/>{error?<span>{error}</span>:null}</label>),
 Select:React.forwardRef(({label,options=[],error,...p}:any,ref:any)=><label>{label}<select ref={ref} aria-label={label} {...p}>{options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{error?<span>{error}</span>:null}</label>)
}));
vi.mock("../forms/ItemMediaVariantsSection",()=>({ItemMediaVariantsSection:(p:any)=><div><button type="button" onClick={p.onAddVariant}>add-variant</button><button type="button" onClick={()=>p.onVariantChange(0,{name:"Large",price:"120"})}>change-variant</button><button type="button" onClick={()=>p.onRemoveVariant(0)}>remove-variant</button><button type="button" onClick={()=>p.onNewImageUrl(" https://x/img.jpg ")}>set-image</button><button type="button" onClick={p.onAddImage}>add-image</button><button type="button" onClick={()=>p.onRemoveImage(0)}>remove-image</button></div>}));
vi.mock("../forms/ItemAssociationsSection",()=>({ItemAssociationsSection:(p:any)=><div><button type="button" onClick={()=>p.toggle("11111111-1111-4111-8111-111111111111","groups")}>group</button><button type="button" onClick={()=>p.toggle("22222222-2222-4222-8222-222222222222","tags")}>tag</button><button type="button" onClick={()=>p.toggle("33333333-3333-4333-8333-333333333333","allergens")}>allergen</button></div>}));
vi.mock("../RecipeBuilder",()=>({RecipeBuilder:()=> <div>RecipeBuilder</div>}));
vi.mock("../ScheduleManager",()=>({ScheduleManager:()=> <div>ScheduleManager</div>}));
vi.mock("../BranchOverridesPanel",()=>({BranchOverridesPanel:()=> <div>BranchOverridesPanel</div>}));
vi.mock("../ChannelOverridesPanel",()=>({ChannelOverridesPanel:()=> <div>ChannelOverridesPanel</div>}));
vi.mock("../PriceRulesPanel",()=>({PriceRulesPanel:()=> <div>PriceRulesPanel</div>}));
vi.mock("../VariantAvailabilityPanel",()=>({VariantAvailabilityPanel:()=> <div>VariantAvailabilityPanel</div>}));
vi.mock("../VariantModifierPricingPanel",()=>({VariantModifierPricingPanel:()=> <div>VariantModifierPricingPanel</div>}));
vi.mock("../forms/MenuMembershipsEditor",()=>({MenuMembershipsEditor:()=> <div>MenuMembershipsEditor</div>}));
vi.mock("../forms/StationRoutingEditor",()=>({StationRoutingEditor:()=> <div>StationRoutingEditor</div>}));
vi.mock("../FoodTypeDot",()=>({FoodTypeDot:()=> <div>FoodTypeDot</div>}));
import { ItemFormModal } from "../ItemFormModal";

const editItem:any={id:"i1",branchId:null,name:"Burger",description:"Old",basePrice:"100",manualCost:"40",taxRate:"5",taxMode:"EXCLUSIVE",foodType:"NON_VEG",spiceLevel:"HOT",sku:"B1",prepTimeMinutes:10,hsnCode:"123",status:"ACTIVE",availabilityReason:null,enableRecipeDeduction:true,displayMode:"STANDARD",effectiveFrom:null,pricingMode:"FIXED",weightUnit:null,openPriceMin:null,openPriceMax:null,supportsZones:false,zonePricingRule:"HIGHER",manualStockCount:null,variants:[{id:"55555555-5555-4555-8555-555555555555",name:"Small",price:"90"}],images:[{url:"https://x/old.jpg"}],modifierGroupLinks:[{modifierGroupId:"11111111-1111-4111-8111-111111111111"}],tagLinks:[{tagId:"22222222-2222-4222-8222-222222222222"}],allergenLinks:[{allergenId:"33333333-3333-4333-8333-333333333333"}]};

describe("ItemFormModal coverage",()=>{
 beforeEach(()=>{vi.clearAllMocks();m.groups=[{id:"11111111-1111-4111-8111-111111111111",name:"Required",minSelections:1}];m.tags=[{id:"22222222-2222-4222-8222-222222222222"}];m.allergens=[{id:"33333333-3333-4333-8333-333333333333"}];m.categories=[{id:"44444444-4444-4444-8444-444444444444",name:"Main"}];m.save.mockImplementation((_a:any,o:any)=>o?.onSuccess?.());});
 it("creates an item with advanced pricing, associations, media and preset",async()=>{const close=vi.fn();render(<ItemFormModal categoryId="44444444-4444-4444-8444-444444444444" item={null} onClose={close}/>);fireEvent.change(screen.getByLabelText("Item name"),{target:{value:" Pizza "}});fireEvent.change(screen.getByLabelText("Selling price (₹)"),{target:{value:"200"}});fireEvent.change(screen.getByLabelText("Cost (₹)"),{target:{value:"80"}});fireEvent.change(screen.getByLabelText("Tax rate (%)"),{target:{value:"12"}});fireEvent.change(screen.getByLabelText("Tax mode"),{target:{value:"INCLUSIVE"}});fireEvent.click(screen.getByRole("button",{name:/Non-Veg/}));fireEvent.change(screen.getByLabelText("Spice level"),{target:{value:"MEDIUM"}});fireEvent.change(screen.getByLabelText("Status"),{target:{value:"OUT_OF_STOCK"}});fireEvent.change(screen.getByLabelText("Reason (optional)"),{target:{value:" sold out "}});fireEvent.click(screen.getByText("Show advanced options"));fireEvent.change(screen.getByLabelText("Pricing mode"),{target:{value:"OPEN"}});fireEvent.change(screen.getByLabelText("Minimum manual price"),{target:{value:"100"}});fireEvent.change(screen.getByLabelText("Maximum manual price"),{target:{value:"300"}});fireEvent.click(screen.getByLabelText(/Supports split zones/));fireEvent.change(screen.getByLabelText("Zone pricing rule"),{target:{value:"AVERAGE"}});fireEvent.click(screen.getByLabelText(/Track finite stock/));fireEvent.change(screen.getByLabelText("Current stock count"),{target:{value:"7"}});fireEvent.click(screen.getByText("add-variant"));fireEvent.click(screen.getByText("change-variant"));fireEvent.click(screen.getByText("set-image"));fireEvent.click(screen.getByText("add-image"));fireEvent.click(screen.getByText("Apply Build-Your-Own preset"));fireEvent.click(screen.getByText("tag"));fireEvent.click(screen.getByText("allergen"));fireEvent.change(screen.getByLabelText("Effective from (optional)"),{target:{value:"2030-01-01T10:00"}});fireEvent.click(screen.getByRole("button",{name:"Add Item"}));await waitFor(()=>expect(m.save).toHaveBeenCalled());expect(m.save.mock.calls[0]![0]).toEqual(expect.objectContaining({item:null,payload:expect.objectContaining({categoryId:"44444444-4444-4444-8444-444444444444",name:"Pizza",basePrice:200,manualCost:80,pricingMode:"OPEN",openPriceMin:100,openPriceMax:300,supportsZones:true,zonePricingRule:"AVERAGE",manualStockCount:7,taxMode:"INCLUSIVE",displayMode:"GUIDED_BUILDER",modifierGroupIds:["11111111-1111-4111-8111-111111111111"],tagIds:["22222222-2222-4222-8222-222222222222"],allergenIds:["33333333-3333-4333-8333-333333333333"],variants:[expect.objectContaining({name:"Large",price:120})],imageUrls:["https://x/img.jpg"]})}));expect(close).toHaveBeenCalled();});
 it("edits item, renders edit-only modules and clears advanced fixed values",async()=>{const close=vi.fn();render(<ItemFormModal categoryId="44444444-4444-4444-8444-444444444444" item={editItem} onClose={close}/>);expect(screen.getByRole("dialog",{name:"Edit Menu Item"})).toBeTruthy();fireEvent.click(screen.getByText("Show advanced options"));for(const text of ["MenuMembershipsEditor","RecipeBuilder","ScheduleManager","ChannelOverridesPanel","VariantAvailabilityPanel","VariantModifierPricingPanel","PriceRulesPanel","BranchOverridesPanel","StationRoutingEditor"]) expect(screen.getByText(text)).toBeTruthy();fireEvent.change(screen.getByLabelText("Pricing mode"),{target:{value:"WEIGHT_BASED"}});fireEvent.change(screen.getByLabelText("Rate unit"),{target:{value:"LB"}});fireEvent.click(screen.getByLabelText(/Track finite stock/));fireEvent.click(screen.getByRole("button",{name:"Save Changes"}));await waitFor(()=>expect(m.save).toHaveBeenCalled());expect(m.save.mock.calls[0]![0].payload).toEqual(expect.objectContaining({pricingMode:"WEIGHT_BASED",weightUnit:"LB",openPriceMin:null,openPriceMax:null,manualStockCount:null}));fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(close).toHaveBeenCalled();});
});
