import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const h=vi.hoisted(()=>({categories:[] as any[],loading:false,add:vi.fn(),rename:vi.fn(),del:vi.fn()}));
vi.mock("@/features/menu/hooks/useMenuCategories",()=>({useMenuCategories:()=>({data:h.categories,isLoading:h.loading})}));
vi.mock("@/features/menu/hooks/useAddCategory",()=>({useAddCategory:()=>({isPending:false,mutate:h.add})}));
vi.mock("@/features/menu/hooks/useRenameCategory",()=>({useRenameCategory:()=>({isPending:false,mutate:h.rename})}));
vi.mock("@/features/menu/hooks/useDeleteCategory",()=>({useDeleteCategory:()=>({mutate:h.del})}));
vi.mock("../SubRecipeManager",()=>({SubRecipeManager:()=> <div>Sub recipe manager</div>}));
vi.mock("../ItemFormModal",()=>({ItemFormModal:({item,onClose}:any)=><div role="dialog"><span>Editing {item.name}</span><button onClick={onClose}>Close editor</button></div>}));
vi.mock("@pos/ui",()=>({
 Button:({children,loading:_l,...p}:any)=><button {...p}>{children}</button>,Card:({children}:any)=><div>{children}</div>,EmptyState:({title,description,action}:any)=><div><span>{title}</span><span>{description}</span>{action}</div>,IconButton:({icon:_i,...p}:any)=><button {...p}/>,Input:({label,...p}:any)=><label>{label}<input aria-label={label} {...p}/></label>,Modal:({open,title,children}:any)=>open?<div role="dialog"><h2>{title}</h2>{children}</div>:null,Spinner:()=> <span>spinner</span>,Grid:({children}:any)=><div>{children}</div>,SearchInput:({onClear,...p}:any)=><div><input {...p}/><button onClick={onClear}>Clear search</button></div>
}));
import { MenuCategoriesSection } from "../MenuCategoriesSection";
import { MenuSpecializedSection } from "../MenuSpecializedSection";
describe("secondary menu sections coverage",()=>{beforeEach(()=>{vi.clearAllMocks();h.categories=[];h.loading=false;h.add.mockImplementation((_v:any,o:any)=>o?.onSuccess?.());h.rename.mockImplementation((_v:any,o:any)=>o?.onSuccess?.());});
 it("covers categories loading/empty/add/edit/delete/template",async()=>{h.loading=true;const saveTemplate=vi.fn();const {rerender}=render(<MenuCategoriesSection onSaveTemplate={saveTemplate}/>);expect(screen.getByText("spinner")).toBeTruthy();h.loading=false;rerender(<MenuCategoriesSection onSaveTemplate={saveTemplate}/>);expect(screen.getByText("No categories")).toBeTruthy();fireEvent.click(screen.getAllByRole("button",{name:"Add Category"})[0]!);fireEvent.change(screen.getByLabelText("Category name"),{target:{value:" Starters "}});fireEvent.click(screen.getAllByRole("button",{name:"Add Category"}).at(-1)!);await waitFor(()=>expect(h.add).toHaveBeenCalledWith("Starters",expect.anything()));h.categories=[{id:"c1",name:"Mains",menuItems:[{id:"i1"}]}];rerender(<MenuCategoriesSection onSaveTemplate={saveTemplate}/>);expect(screen.getByText("1 items")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Save as Template"}));expect(saveTemplate).toHaveBeenCalledWith({id:"c1",name:"Mains"});fireEvent.click(screen.getByLabelText("Rename Mains"));fireEvent.change(screen.getByLabelText("Category name"),{target:{value:" Entrees "}});fireEvent.click(screen.getByRole("button",{name:"Save"}));await waitFor(()=>expect(h.rename).toHaveBeenCalledWith({id:"c1",name:"Entrees"},expect.anything()));vi.spyOn(window,"confirm").mockReturnValue(true);fireEvent.click(screen.getByLabelText("Delete Mains"));expect(h.del).toHaveBeenCalledWith("c1");});
 it("covers specialized recipe and availability search/editor states",()=>{h.categories=[{id:"c1",name:"Mains",menuItems:[{id:"i1",name:"Latte"},{id:"i2",name:"Tea"}]}];const {rerender}=render(<MenuSpecializedSection mode="recipes"/>);expect(screen.getByText("Sub recipe manager")).toBeTruthy();fireEvent.change(screen.getByLabelText("Search items for recipes"),{target:{value:"lat"}});expect(screen.getByText("Latte")).toBeTruthy();expect(screen.queryByText("Tea")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Manage Recipe"}));expect(screen.getByText("Editing Latte")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Close editor"}));fireEvent.click(screen.getByRole("button",{name:"Clear search"}));expect(screen.getByText("Tea")).toBeTruthy();rerender(<MenuSpecializedSection mode="availability"/>);expect(screen.queryByText("Sub recipe manager")).toBeNull();fireEvent.click(screen.getAllByRole("button",{name:"Manage Availability"})[0]!);expect(screen.getByRole("dialog")).toBeTruthy();});
 it("covers specialized loading and no-match states",()=>{h.loading=true;const {rerender}=render(<MenuSpecializedSection mode="availability"/>);expect(screen.getByText("spinner")).toBeTruthy();h.loading=false;h.categories=[];rerender(<MenuSpecializedSection mode="availability"/>);expect(screen.getByText("No matching menu items.")).toBeTruthy();});
});
