import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({promos:[] as any[],stats:{} as Record<string,any>,create:vi.fn(),update:vi.fn(),remove:vi.fn(),invalidate:vi.fn(),categories:[] as any[]}));
vi.mock("@/shared/lib/api-client",()=>({apiClient:{}}));
vi.mock("@/features/menu/hooks/useMenuCategories",()=>({useMenuCategories:()=>({data:mocks.categories})}));
vi.mock("@pos/api-client",()=>({createMenuApi:()=>({listPromotionsFor:vi.fn(),promotionStats:vi.fn(),createPromotion:mocks.create,updatePromotion:mocks.update,removePromotion:mocks.remove})}));
vi.mock("@tanstack/react-query",()=>({
 useQueryClient:()=>({invalidateQueries:mocks.invalidate}),
 useQuery:({queryKey}:any)=>({data:queryKey?.at(-1)==="stats"?undefined:(queryKey?.includes("stats")?mocks.stats[queryKey[2]]:mocks.promos)}),
 useMutation:(opts:any)=>({isPending:false,mutate:async(arg?:any)=>{const out=await opts.mutationFn(arg);opts.onSuccess?.(out);}})
}));
vi.mock("@pos/ui",()=>({Button:({children,loading:_l,...p}:any)=><button {...p}>{children}</button>,Input:({label,...p}:any)=><label>{label}<input aria-label={label} {...p}/></label>,Select:({label,options=[],...p}:any)=><label>{label}<select aria-label={label} {...p}>{options.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}));
import { PromotionsSection } from "../PromotionsSection";
const promo:any={id:"p1",name:"Lunch 10",ruleType:"PERCENTAGE",scope:"ORDER",value:"10",couponCode:"LUNCH",startDate:null,endDate:null,startTime:null,endTime:null,maxUsesTotal:null,maxUsesPerCustomer:null,triggerCategoryId:null,triggerMenuItemId:null,rewardCategoryId:null,rewardMenuItemId:null,triggerQuantity:null,rewardQuantity:null,rewardDiscountPercent:null,stackableWithLoyalty:true,isActive:true};

describe("PromotionsSection coverage",()=>{
 beforeEach(()=>{vi.clearAllMocks();mocks.promos=[promo,{...promo,id:"p2",name:"Buy 2",ruleType:"BOGO",scope:"ORDER",value:null,couponCode:null,triggerMenuItemId:"i1",triggerQuantity:2,rewardQuantity:1,rewardDiscountPercent:100,stackableWithLoyalty:false,isActive:false}];mocks.stats={p1:{uses:3,discountAmount:"12.50"},p2:{uses:0,discountAmount:"0"}};mocks.categories=[{id:"c1",name:"Drinks",menuItems:[{id:"i1",name:"Tea"},{id:"i2",name:"Coffee"}]}];mocks.create.mockResolvedValue({});mocks.update.mockResolvedValue({});mocks.remove.mockResolvedValue({});});
 it("creates ordinary scoped promotion with limits and uppercase coupon",async()=>{render(<PromotionsSection/>);expect((screen.getByRole("button",{name:"Create promotion"}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText("Name"),{target:{value:"  Friday "}});fireEvent.change(screen.getByLabelText("Scope"),{target:{value:"CATEGORY"}});fireEvent.change(screen.getByLabelText("Category"),{target:{value:"c1"}});fireEvent.change(screen.getByLabelText("Percent off"),{target:{value:"15"}});fireEvent.change(screen.getByLabelText("Coupon code (optional)"),{target:{value:"fri15"}});fireEvent.change(screen.getByLabelText("Start date"),{target:{value:"2026-09-10"}});fireEvent.change(screen.getByLabelText("End date"),{target:{value:"2026-09-20"}});fireEvent.change(screen.getByLabelText("Start time"),{target:{value:"10:00"}});fireEvent.change(screen.getByLabelText("End time"),{target:{value:"14:00"}});fireEvent.change(screen.getByLabelText("Max uses total"),{target:{value:"100"}});fireEvent.change(screen.getByLabelText("Max uses / customer"),{target:{value:"2"}});fireEvent.click(screen.getByLabelText(/Stackable with loyalty/));fireEvent.click(screen.getByRole("button",{name:"Create promotion"}));await waitFor(()=>expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({name:"  Friday ",scope:"CATEGORY",value:15,scopeCategoryId:"c1",couponCode:"FRI15",maxUsesTotal:100,maxUsesPerCustomer:2,stackableWithLoyalty:false})));expect(mocks.invalidate).toHaveBeenCalled();});
 it("creates BOGO item/category rewards and validates required targets",async()=>{render(<PromotionsSection/>);fireEvent.change(screen.getByLabelText("Name"),{target:{value:"BOGO"}});fireEvent.change(screen.getByLabelText("Type"),{target:{value:"BOGO"}});expect((screen.getByRole("button",{name:"Create promotion"}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText("Buy item"),{target:{value:"i1"}});fireEvent.change(screen.getByLabelText("Reward target"),{target:{value:"ITEM"}});fireEvent.change(screen.getByLabelText("Reward item"),{target:{value:"i2"}});fireEvent.change(screen.getByLabelText("Buy quantity"),{target:{value:"3"}});fireEvent.change(screen.getByLabelText("Reward quantity"),{target:{value:"2"}});fireEvent.change(screen.getByLabelText("Reward discount %"),{target:{value:"50"}});fireEvent.click(screen.getByRole("button",{name:"Create promotion"}));await waitFor(()=>expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ruleType:"BOGO",triggerMenuItemId:"i1",rewardMenuItemId:"i2",triggerQuantity:3,rewardQuantity:2,rewardDiscountPercent:50})));fireEvent.change(screen.getByLabelText("Name"),{target:{value:"BOGO2"}});fireEvent.change(screen.getByLabelText("Buy target"),{target:{value:"CATEGORY"}});fireEvent.change(screen.getByLabelText("Buy category"),{target:{value:"c1"}});fireEvent.change(screen.getByLabelText("Reward target"),{target:{value:"CATEGORY"}});fireEvent.change(screen.getByLabelText("Reward category"),{target:{value:"c1"}});fireEvent.click(screen.getByRole("button",{name:"Create promotion"}));await waitFor(()=>expect(mocks.create).toHaveBeenCalledTimes(2));});
 it("edits, cancels, toggles active state, deletes and renders stats placeholders",async()=>{render(<PromotionsSection/>);expect(screen.getAllByText("Loading stats…").length).toBeGreaterThan(0);fireEvent.click(screen.getAllByRole("button",{name:"Edit"})[0]!);expect((screen.getByLabelText("Name") as HTMLInputElement).value).toBe("Lunch 10");expect(screen.getByRole("button",{name:"Save promotion"})).toBeTruthy();fireEvent.change(screen.getByLabelText("Type"),{target:{value:"FIXED_AMOUNT"}});fireEvent.change(screen.getByLabelText("Amount off"),{target:{value:"25"}});fireEvent.click(screen.getByRole("button",{name:"Save promotion"}));await waitFor(()=>expect(mocks.update).toHaveBeenCalled());fireEvent.click(screen.getAllByRole("button",{name:"Edit"})[0]!);fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("button",{name:"Disable"}));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith("p1",{isActive:false}));fireEvent.click(screen.getByRole("button",{name:"Enable"}));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith("p2",{isActive:true}));fireEvent.click(screen.getAllByRole("button",{name:"Delete"})[0]!);await waitFor(()=>expect(mocks.remove).toHaveBeenCalledWith("p1"));});
});
