import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
const m=vi.hoisted(()=>({recipe:[] as any[],loading:false,inventory:[] as any[],subs:[] as any[],save:vi.fn(),err:vi.fn()}));
vi.mock("@/features/menu/hooks/useMenuItemRecipe",()=>({useMenuItemRecipe:()=>({data:m.recipe,isLoading:m.loading})}));
vi.mock("@/features/inventory/hooks/useInventoryItems",()=>({useInventoryItems:()=>({data:{items:m.inventory}})}));
vi.mock("@/features/menu/hooks/useSubRecipes",()=>({useSubRecipes:()=>({data:m.subs})}));
vi.mock("@/features/menu/hooks/useSaveRecipe",()=>({useSaveRecipe:()=>({isPending:false,mutate:m.save})}));
vi.mock("@/shared/lib/notify",()=>({notifyError:m.err}));
import { RecipeBuilder } from "../RecipeBuilder";
const item:any={id:"i1",name:"Burger",variants:[{id:"v1",name:"Large"}],modifierGroupLinks:[{group:{name:"Extras",options:[{id:"o1",name:"Cheese"}]}}]};
describe("RecipeBuilder coverage",()=>{
 beforeEach(()=>{vi.clearAllMocks();m.loading=false;m.inventory=[{id:"inv1",name:"Flour",unit:"GRAMS",currentStock:2},{id:"inv2",name:"Oil",unit:"ML",currentStock:100}];m.subs=[{id:"s1",name:"Sauce",yieldUnit:"ML"},{id:"s2",name:"Dough",yieldUnit:"GRAMS"}];m.recipe=[{inventoryItemId:"inv1",subRecipeId:null,variantId:null,modifierOptionId:null,quantityRequired:"3",unit:"GRAMS",yieldPercent:null,isOptional:false}];m.save.mockImplementation((_x:any,o:any)=>o?.onSuccess?.());});
 it("loads recipe, edits scopes/sources and saves valid ingredients",async()=>{render(<RecipeBuilder item={item}/>);expect(screen.getByText("Saved")).toBeTruthy();expect(document.querySelector(".text-warning")).toBeTruthy();const selects=screen.getAllByRole("combobox");fireEvent.change(selects[0]!,{target:{value:"sub-recipe"}});fireEvent.change(screen.getAllByRole("combobox")[1]!,{target:{value:"s2"}});fireEvent.change(screen.getByLabelText("Quantity for recipe row 1"),{target:{value:"2"}});const all=screen.getAllByRole("combobox");const scope=all.find(x=>Array.from(x.querySelectorAll("option")).some(o=>o.value==="variant"))!;fireEvent.change(scope,{target:{value:"variant"}});const yieldInput=screen.getByPlaceholderText("100");fireEvent.change(yieldInput,{target:{value:"80"}});fireEvent.click(screen.getByRole("checkbox"));fireEvent.click(screen.getByText("Save recipe"));await waitFor(()=>expect(m.save).toHaveBeenCalled());expect(m.save.mock.calls[0]![0][0]).toEqual(expect.objectContaining({subRecipeId:"s2",inventoryItemId:null,variantId:"v1",quantity:2,yieldPercent:80,isOptional:true}));});
 it("adds inventory/sub-recipe rows, modifier scope and removes rows",()=>{m.recipe=[];const {rerender}=render(<RecipeBuilder item={item}/>);fireEvent.click(screen.getByText(/Add ingredient/));expect(screen.getByLabelText("Quantity for recipe row 1")).toBeTruthy();let scope=screen.getAllByRole("combobox").find(x=>Array.from(x.querySelectorAll("option")).some(o=>o.value==="modifier"))!;fireEvent.change(scope,{target:{value:"modifier"}});expect(screen.getByText(/Extras · Cheese/)).toBeTruthy();fireEvent.click(screen.getByLabelText("Remove recipe row 1"));expect(screen.queryByLabelText("Quantity for recipe row 1")).toBeNull();m.inventory=[];rerender(<RecipeBuilder item={item}/>);fireEvent.click(screen.getByText(/Add ingredient/));expect(screen.getByDisplayValue("Sauce")).toBeTruthy();});
 it("handles loading and no available ingredient sources",()=>{m.loading=true;m.recipe=[];m.inventory=[];m.subs=[];const {rerender}=render(<RecipeBuilder item={{...item,variants:[],modifierGroupLinks:[]}}/>);expect(screen.getByText("Loading…")).toBeTruthy();m.loading=false;rerender(<RecipeBuilder item={{...item,variants:[],modifierGroupLinks:[]}}/>);fireEvent.click(screen.getByText(/Add ingredient/));expect(m.err).toHaveBeenCalledWith(undefined,"Add an inventory item or sub-recipe first");});
});
