import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { OrderStatus } from "../OrderStatus";
const baseOrder=(over:any={})=>({id:"order123456",status:"OPEN",subtotal:"20",taxAmount:"2",discountAmount:"1",totalAmount:"21",payments:[],kitchenTickets:[{id:"k1",ticketNumber:1,status:"FIRED"}],items:[{id:"i1",quantity:2,menuItemName:"Pizza",variantName:"Large",subtotal:"20",fulfillmentType:"DINE_IN",modifiers:[{quantity:2,name:"Cheese"}]}],...over} as any);
const props=(over:any={})=>({order:baseOrder(),mode:"DINE_IN" as const,table:"7",estimatedTime:"10 min",onMenu:vi.fn(),live:true,onRequest:vi.fn(),requestBusy:false,requestMessage:null,...over});
describe("OrderStatus exhaustive",()=>{
 it("renders received flow, service requests, details, discount and navigation",()=>{const p=props();render(<OrderStatus {...p}/>);expect(screen.getByText("Order received.")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/Call waiter/i}));expect(p.onRequest).toHaveBeenCalledWith("CALL_WAITER");fireEvent.click(screen.getByRole("button",{name:/Request bill/i}));expect(p.onRequest).toHaveBeenCalledWith("BILL");fireEvent.click(screen.getAllByRole("button",{name:/Menu/i})[0]!);expect(p.onMenu).toHaveBeenCalled();expect(screen.getByText(/2 × Cheese/)).toBeTruthy();expect(screen.getByText(/Discount/)).toBeTruthy();});
 it("covers preparing, ready dine-in and takeaway, reconnect and service filtering",()=>{const {rerender}=render(<OrderStatus {...props({live:false,order:baseOrder({kitchenTickets:[{id:"k",ticketNumber:1,status:"PREPARING"}]})})}/>);expect(screen.getByText("It's cooking.")).toBeTruthy();expect(screen.getByText("Reconnecting")).toBeTruthy();rerender(<OrderStatus {...props({order:baseOrder({kitchenTickets:[{id:"k",ticketNumber:1,status:"READY"}]})})}/>);expect(screen.getByText("It's ready.")).toBeTruthy();rerender(<OrderStatus {...props({mode:"TAKEAWAY",table:"Takeaway",order:baseOrder({kitchenTickets:[{id:"k",ticketNumber:1,status:"READY"}]})})}/>);expect(screen.getByText("Ready for pickup.")).toBeTruthy();expect(screen.queryByRole("button",{name:/Request bill/i})).toBeNull();});
 it("covers payment panel and busy state",()=>{const pay=vi.fn();const order=baseOrder({status:"PENDING_PAYMENT",payments:[{method:"RAZORPAY",status:"PENDING"}],kitchenTickets:[{id:"k",ticketNumber:1,status:"PENDING_PAYMENT"}]});const {rerender}=render(<OrderStatus {...props({order,mode:"TAKEAWAY",table:"Takeaway",onPay:pay})}/>);fireEvent.click(screen.getByRole("button",{name:/Pay/}));expect(pay).toHaveBeenCalled();rerender(<OrderStatus {...props({order,mode:"TAKEAWAY",table:"Takeaway",onPay:pay,payBusy:true})}/>);expect(screen.getByRole("button",{name:/Opening payment/})).toBeTruthy();});
 it("covers terminal statuses and kitchen rounds/status labels",()=>{for(const [status,title] of [["PAID","All done."],["CLOSED","All done."],["CANCELLED","Order cancelled."]] as const){const order=baseOrder({status,kitchenTickets:[{id:"a",ticketNumber:1,status:"PREPARING"},{id:"b",ticketNumber:2,status:"SERVED"}],discountAmount:"0",items:[{id:"x",quantity:1,menuItemName:"Soup",variantName:null,subtotal:"5",fulfillmentType:"TAKEAWAY",modifiers:[]}]});const {unmount}=render(<OrderStatus {...props({order})}/>);expect(screen.getByText(title)).toBeTruthy();expect(screen.getByText("Kitchen rounds")).toBeTruthy();unmount();}});
 it("covers no tickets/items and request message/busy",()=>{const p=props({order:baseOrder({kitchenTickets:[],items:undefined}),requestBusy:true,requestMessage:"Sent"});render(<OrderStatus {...p}/>);expect(screen.getByText("Sent")).toBeTruthy();expect(screen.getByText(/0 items/)).toBeTruthy();});
});
it("scrolls to customer service from bottom nav",()=>{const scroll=vi.fn();const original=document.getElementById.bind(document);vi.spyOn(document,"getElementById").mockImplementation((id)=>id==="customer-service"?({scrollIntoView:scroll} as any):original(id));render(<OrderStatus {...props()}/>);fireEvent.click(screen.getByRole("button",{name:/Service/i}));expect(scroll).toHaveBeenCalled();vi.restoreAllMocks();});
