import type {
  BusinessBranchFormValues,
  FranchiseBusinessFormValues,
  OrganizationBusinessFormValues,
} from "@pos/validation";

export const inputClass =
  "w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-text-primary";
export const checkboxClass = "h-4 w-4 rounded border-border text-primary";

export const organizationDefaults: OrganizationBusinessFormValues = {
  name: "",
  businessType: "INDEPENDENT_RESTAURANT",
  country: "IN",
  timezone: "Asia/Kolkata",
  currency: "INR",
  primaryContactName: "",
  businessEmail: "",
  businessPhone: "",
  addressLine1: "",
  city: "",
  stateProvince: "",
  postalCode: "",
  legalName: "",
  addressLine2: "",
  website: "",
  taxRegistrationNumber: "",
  gstin: "",
  pan: "",
  companyRegistrationNumber: "",
  logoUrl: "",
};
export const franchiseDefaults: FranchiseBusinessFormValues = {
  name: "",
  cuisineTypes: [],
  businessModel: "RESTAURANT",
  defaultTaxMode: "EXCLUSIVE",
  defaultCurrency: "INR",
  defaultTimezone: "Asia/Kolkata",
  dineInEnabled: true,
  takeawayEnabled: true,
  deliveryEnabled: true,
  customerQrEnabled: true,
  tableManagementEnabled: true,
  kdsEnabled: true,
  waiterServiceEnabled: true,
  displayName: "",
  description: "",
  supportEmail: "",
  supportPhone: "",
  website: "",
  logoUrl: "",
  primaryBrandImageUrl: "",
  defaultTaxRate: null,
  serviceChargePercent: null,
  serviceChargeTaxable: false,
  roundingPolicy: "NONE",
  courseSequencingEnabled: false,
};
export const branchDefaults: BusinessBranchFormValues = {
  name: "",
  code: "",
  status: "ACTIVE",
  addressLine1: "",
  addressLine2: "",
  city: "",
  stateProvince: "",
  postalCode: "",
  country: "IN",
  timezone: "Asia/Kolkata",
  phone: "",
  dineInEnabled: true,
  takeawayEnabled: true,
  deliveryEnabled: true,
  customerQrEnabled: true,
  tablesEnabled: true,
  kdsEnabled: true,
  waiterAppEnabled: true,
  managerName: "",
  email: "",
  openingTime: "",
  closingTime: "",
  weeklyOperatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
  taxOverride: null,
  serviceChargeOverride: null,
  invoicePrefix: "",
  receiptFooter: "",
  inventoryTrackingEnabled: true,
  negativeStockPolicy: "BLOCK",
};
