import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { CtaBanner } from "@/components/marketing/CtaBanner";
export const metadata: Metadata = { title: "Implementation & Onboarding", description: "Plan branches, menus, staff, kitchen and launch readiness with Servora." };
const phases = [
  ["Discover", "Map locations, order modes, billing, payment, staff and kitchen requirements before configuration starts."],
  ["Configure", "Set up organization context, branches, taxes, payment choices, roles, tables and kitchen stations."],
  ["Bring the menu", "Import or build categories, items, modifiers, variants, combos, pricing, recipes and availability rules."],
  ["Practice the shift", "Walk through guest, waiter, kitchen, billing, refund and manager-approval scenarios with the team."],
  ["Launch and learn", "Start with a clear support route, monitor live operations and refine menus, permissions and branch settings."],
];
export default function OnboardingPage(){return <><section className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><div className="max-w-4xl"><p className="text-sm font-semibold text-primary">Implementation and onboarding</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Prepare the whole restaurant, not just the software.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-text-secondary">A strong launch aligns branches, menus, staff permissions, payment flows and kitchen routing before the first live shift.</p></div><ol className="mt-14 space-y-5">{phases.map(([title,text],index)=><li key={title} className="grid gap-4 rounded-2xl border border-border bg-surface p-6 sm:grid-cols-[auto_1fr]"><span className="flex size-10 items-center justify-center rounded-full bg-primary text-sm font-bold text-white">{index+1}</span><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-text-secondary">{text}</p></div></li>)}</ol><section className="mt-14 rounded-3xl bg-[#111827] p-8 text-white"><h2 className="text-2xl font-semibold">Bring these to the first planning session</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Branch and service model", "Existing menu or export", "Tax and service-charge rules", "Payment requirements", "Staff roles", "Kitchen stations and routing", "Devices and network", "Target launch window"].map(item=><div key={item} className="flex items-center gap-3"><CheckCircle2 className="text-violet-300" size={19}/><span>{item}</span></div>)}</div></section></section><CtaBanner title="Plan a confident Servora rollout." /></>}
