export const CUSTOMER_ORDER_MAX_RECONNECT_DELAY_MS = 30_000;
export const CUSTOMER_ORDER_INITIAL_RECONNECT_DELAY_MS = 1_000;
export const CUSTOMER_ORDER_TICKET_STEPS = ["FIRED", "PREPARING", "READY", "SERVED"] as const;
