import { beforeEach, describe, expect, it, vi } from "vitest";
const m=vi.hoisted(()=>({membershipFindMany:vi.fn(),orgFindFirst:vi.fn(),tenantFindFirst:vi.fn(),roleFindFirst:vi.fn(),branchFindFirst:vi.fn(),transaction:vi.fn(),insert:vi.fn(),insertValues:vi.fn(),insertReturning:vi.fn(),update:vi.fn(),updateSet:vi.fn(),updateWhere:vi.fn(),updateReturning:vi.fn()}));
vi.mock("@/db",()=>{const tx={insert:m.insert};m.transaction.mockImplementation(async(fn:Function)=>fn(tx));m.insert.mockImplementation(()=>({values:m.insertValues}));m.insertValues.mockImplementation(()=>({returning:m.insertReturning,then:Promise.resolve(undefined).then.bind(Promise.resolve(undefined))}));m.update.mockImplementation(()=>({set:m.updateSet}));m.updateSet.mockImplementation(()=>({where:m.updateWhere}));m.updateWhere.mockImplementation(()=>({returning:m.updateReturning}));return{db:{query:{tenantMemberships:{findMany:m.membershipFindMany},organizationMemberships:{findFirst:m.orgFindFirst},tenants:{findFirst:m.tenantFindFirst},roles:{findFirst:m.roleFindFirst},branches:{findFirst:m.branchFindFirst}},transaction:m.transaction,insert:m.insert,update:m.update}}});
import { tenantRepository } from "../tenant.repository";

describe("tenant repository comprehensive coverage",()=>{
 beforeEach(()=>{vi.clearAllMocks();m.membershipFindMany.mockImplementation(async(o?:any)=>{o?.orderBy?.({createdAt:"created"},{asc:(v:unknown)=>v});return[{id:"m1"}]});m.orgFindFirst.mockResolvedValue({id:"om1"});m.tenantFindFirst.mockResolvedValue({id:"t1"});m.roleFindFirst.mockResolvedValue({id:"r1"});m.branchFindFirst.mockResolvedValue({id:"b1"});m.insertReturning.mockResolvedValue([{id:"t1"}]);m.updateReturning.mockResolvedValue([{id:"t1"}]);});
 it("covers membership/org/tenant/role/branch reads",async()=>{await expect(tenantRepository.findMembershipsByUserId("u1")).resolves.toEqual([{id:"m1"}]);await expect(tenantRepository.findOrganizationMembership("u1","o1")).resolves.toEqual({id:"om1"});await expect(tenantRepository.findById("t1")).resolves.toEqual({id:"t1"});await expect(tenantRepository.findRoleByName("OWNER")).resolves.toEqual({id:"r1"});await expect(tenantRepository.branchBelongsToTenant("t1","b1")).resolves.toEqual({id:"b1"});});
 it("creates tenant and default menu, and throws when tenant insert fails",async()=>{m.insertReturning.mockResolvedValueOnce([{id:"t1"}]);await expect(tenantRepository.create({name:"X"} as any)).resolves.toEqual({id:"t1"});m.insertReturning.mockResolvedValueOnce([]);await expect(tenantRepository.create({name:"X"} as any)).rejects.toThrow("Tenant creation failed");});
 it("updates tenant",async()=>{await expect(tenantRepository.update("t1",{name:"Y"} as any)).resolves.toEqual({id:"t1"});m.updateReturning.mockResolvedValueOnce([]);await expect(tenantRepository.update("t1",{})).resolves.toBeUndefined();});
 it("creates owner membership and throws on insert failure",async()=>{m.insertReturning.mockResolvedValueOnce([{id:"mem1"}]);await expect(tenantRepository.createOwnerMembership("u1","t1","r1")).resolves.toEqual({id:"mem1"});m.insertReturning.mockResolvedValueOnce([]);await expect(tenantRepository.createOwnerMembership("u1","t1","r1")).rejects.toThrow("membership creation failed");});
});
