import{beforeEach,describe,expect,it,vi}from"vitest";const m=vi.hoisted(()=>({branchFindMany:vi.fn(),branchFindFirst:vi.fn(),orderFindFirst:vi.fn(),insert:vi.fn(),insertValues:vi.fn(),insertReturning:vi.fn(),update:vi.fn(),updateSet:vi.fn(),updateWhere:vi.fn(),updateReturning:vi.fn(),transaction:vi.fn(),txUpdate:vi.fn(),txUpdateSet:vi.fn(),txUpdateWhere:vi.fn(),txUpdateReturning:vi.fn()}));
vi.mock("@/db",()=>{m.insert.mockImplementation(()=>({values:m.insertValues}));m.insertValues.mockImplementation(()=>({returning:m.insertReturning}));m.update.mockImplementation(()=>({set:m.updateSet}));m.updateSet.mockImplementation(()=>({where:m.updateWhere}));m.updateWhere.mockImplementation(()=>({returning:m.updateReturning}));m.txUpdate.mockImplementation(()=>({set:m.txUpdateSet}));m.txUpdateSet.mockImplementation(()=>({where:m.txUpdateWhere}));m.txUpdateWhere.mockImplementation(()=>({returning:m.txUpdateReturning,then:Promise.resolve(undefined).then.bind(Promise.resolve(undefined))}));m.transaction.mockImplementation(async(fn:Function)=>fn({update:m.txUpdate}));return{db:{query:{branches:{findMany:m.branchFindMany,findFirst:m.branchFindFirst},orders:{findFirst:m.orderFindFirst}},insert:m.insert,update:m.update,transaction:m.transaction}}});
import{branchRepository}from"../branch.repository";
describe("branch repository comprehensive coverage",()=>{beforeEach(()=>{vi.clearAllMocks();m.branchFindMany.mockResolvedValue([{id:"b1"},{id:"b2"}]);m.branchFindFirst.mockResolvedValue({id:"b1"});m.orderFindFirst.mockResolvedValue({id:"o1"});m.insertReturning.mockResolvedValue([{id:"b1"}]);m.updateReturning.mockResolvedValue([{id:"b1"}]);m.txUpdateReturning.mockResolvedValue([{id:"b1"}]);});
 it("covers list scopes/finds/count",async()=>{await branchRepository.findMany("t1","b1");await branchRepository.findMany("t1",null,["b1"]);await branchRepository.findMany("t1",null,[]);await branchRepository.findByCode("t1","X");await branchRepository.findById("t1","b1");await expect(branchRepository.countActive("t1")).resolves.toBe(2);});
 it("creates with defaults and explicit capabilities",async()=>{await branchRepository.create({tenantId:"t1",name:"X",code:"X",timezone:"UTC",currency:"USD"} as any);await branchRepository.create({tenantId:"t1",name:"X",code:"X",timezone:"UTC",currency:"USD",addressLine1:"A",address:null,dineInEnabled:false,takeawayEnabled:false,deliveryEnabled:false,onlineEnabled:false,tablesEnabled:false,inventoryTrackingEnabled:false,negativeStockPolicy:"ALLOW",customerQrEnabled:false,kdsEnabled:false,waiterAppEnabled:false} as any);expect(m.insertValues).toHaveBeenCalled();});
 it("regenerates QR and deactivates sessions only when branch updated",async()=>{await expect(branchRepository.regenerateTakeawayQr("t1","b1")).resolves.toEqual({id:"b1"});expect(m.txUpdate).toHaveBeenCalledTimes(2);m.txUpdateReturning.mockResolvedValueOnce([]);await expect(branchRepository.regenerateTakeawayQr("t1","missing")).resolves.toBeUndefined();});
 it("updates and checks open order booleans",async()=>{await expect(branchRepository.update("t1","b1",{name:"N"} as any)).resolves.toEqual({id:"b1"});m.updateReturning.mockResolvedValueOnce([]);await expect(branchRepository.update("t1","b1",{})).resolves.toBeUndefined();await expect(branchRepository.hasOpenOrders("t1","b1")).resolves.toBe(true);m.orderFindFirst.mockResolvedValueOnce(undefined);await expect(branchRepository.hasOpenOrders("t1","b1")).resolves.toBe(false);await expect(branchRepository.hasOpenOrdersOfType("t1","b1","DINE_IN")).resolves.toBe(true);m.orderFindFirst.mockResolvedValueOnce(undefined);await expect(branchRepository.hasOpenOrdersOfType("t1","b1","TAKEAWAY")).resolves.toBe(false);});
});
