import { beforeEach,describe,expect,it,vi } from "vitest";
const c=vi.hoisted(()=>({list:vi.fn(),listActive:vi.fn(),create:vi.fn(),listSchedules:vi.fn(),createSchedule:vi.fn(),deleteSchedule:vi.fn(),getById:vi.fn(),update:vi.fn(),publish:vi.fn(),unpublish:vi.fn(),remove:vi.fn()}));
vi.mock("elysia",async(importOriginal)=>{const actual=await importOriginal<typeof import("elysia")>();class FakeElysia{routes:any[]=[];prefix:string;constructor(o:{prefix?:string}={}){this.prefix=o.prefix??"";}use(){return this;}get(p:string,h?:Function,o?:unknown){this.routes.push({method:"GET",path:`${this.prefix}${p}`,handler:h,options:o});return this;}post(p:string,h?:Function,o?:unknown){this.routes.push({method:"POST",path:`${this.prefix}${p}`,handler:h,options:o});return this;}patch(p:string,h?:Function,o?:unknown){this.routes.push({method:"PATCH",path:`${this.prefix}${p}`,handler:h,options:o});return this;}delete(p:string,h?:Function,o?:unknown){this.routes.push({method:"DELETE",path:`${this.prefix}${p}`,handler:h,options:o});return this;}}return{...actual,Elysia:FakeElysia};});
vi.mock("../../../../core/auth",()=>({requireAuthPlugin:()=>({})}));vi.mock("../menu.controller",()=>({menuController:c}));
import { menusRouter } from "@/modules/menu/menus/menu.route";
const auth={tenantId:"t1"} as any;const route=(m:string,p:string)=>(menusRouter as any).routes.find((r:any)=>r.method===m&&r.path===p);
describe("menusRouter coverage",()=>{beforeEach(()=>{vi.clearAllMocks();Object.values(c).forEach((fn:any)=>fn.mockResolvedValue({success:true}));});it("registers eleven endpoints",()=>expect((menusRouter as any).routes).toHaveLength(11));it("executes every route handler",async()=>{
 await route("GET","/api/menu/menus/").handler({auth});await route("GET","/api/menu/menus/active").handler({auth,query:{channel:"STAFF",fulfillmentType:"DINE_IN"}});await route("POST","/api/menu/menus/").handler({auth,body:{name:"M"}});await route("GET","/api/menu/menus/:id/schedules").handler({auth,params:{id:"m1"}});await route("POST","/api/menu/menus/:id/schedules").handler({auth,params:{id:"m1"},body:{scheduleType:"DAILY"}});await route("DELETE","/api/menu/menus/schedules/:id").handler({auth,params:{id:"s1"}});await route("GET","/api/menu/menus/:id").handler({auth,params:{id:"m1"}});await route("PATCH","/api/menu/menus/:id").handler({auth,params:{id:"m1"},body:{name:"N"}});await route("POST","/api/menu/menus/:id/publish").handler({auth,params:{id:"m1"}});await route("POST","/api/menu/menus/:id/unpublish").handler({auth,params:{id:"m1"}});await route("DELETE","/api/menu/menus/:id").handler({auth,params:{id:"m1"}});
 expect(c.listActive).toHaveBeenCalledWith(auth,"STAFF","DINE_IN");expect(c.update).toHaveBeenCalledWith(auth,"m1",{name:"N"});
});});
