export type Solution = { slug: string; type: "role" | "business"; name: string; eyebrow: string; headline: string; description: string; needs: string[]; servora: string[] };
export const solutions: Solution[] = [
  { slug: "owners", type: "role", name: "Restaurant owners", eyebrow: "Solutions by role", headline: "See the business without losing sight of the shift.", description: "Bring sales, menu performance, costs, branches and operating controls into one owner-level view.", needs: ["Reliable daily visibility", "Cost and margin control", "Accountable delegation"], servora: ["Live dashboards and menu engineering", "Recipe-aware inventory and waste", "Roles, approvals and audit logs"] },
  { slug: "managers", type: "role", name: "Restaurant managers", eyebrow: "Solutions by role", headline: "Keep the floor, kitchen and back office moving together.", description: "Manage exceptions, people, availability and active service from a shared operational workspace.", needs: ["Faster exception handling", "Clear team accountability", "Consistent shift execution"], servora: ["Manager approvals and realtime alerts", "Branch-aware staff permissions", "Connected orders, tables and kitchen status"] },
  { slug: "waiters", type: "role", name: "Waiters", eyebrow: "Solutions by role", headline: "Spend less time checking status and more time serving guests.", description: "Take orders, react to ready items and respond to guest requests from a mobile-first flow.", needs: ["Fast order entry", "Visible kitchen progress", "Immediate guest requests"], servora: ["Search, variants, modifiers and combos", "Ready-round notifications", "Water, cutlery, waiter and bill requests"] },
  { slug: "kitchen-teams", type: "role", name: "Kitchen teams", eyebrow: "Solutions by role", headline: "Give every station a focused, live preparation queue.", description: "Keep modifications, notes, timing and void changes visible through every kitchen round.", needs: ["Clear station routing", "Visible urgency", "Accurate change handling"], servora: ["Station-filtered tickets", "Timers and attention states", "Void and stop-preparation alerts"] },
  { slug: "multi-location-operators", type: "role", name: "Multi-location operators", eyebrow: "Solutions by role", headline: "Standardize the system while preserving branch control.", description: "Manage shared operating context, branch-level execution and comparable reporting across a growing group.", needs: ["Central visibility", "Branch flexibility", "Role-aware access"], servora: ["Multi-branch context switching", "Branch menu and channel overrides", "Branch-aware reporting and permissions"] },
  { slug: "quick-service", type: "business", name: "Quick-service restaurants", eyebrow: "Solutions by restaurant", headline: "Move queues quickly from order to kitchen to pickup.", description: "Combine counter, takeaway and digital ordering with a live kitchen and fulfillment workflow.", needs: ["Fast order capture", "Takeaway payment", "Clear pickup progress"], servora: ["POS and QR ordering", "Online takeaway payment", "Kitchen stages and waiter-ready alerts"] },
  { slug: "cafes", type: "business", name: "Cafés", eyebrow: "Solutions by restaurant", headline: "Handle counter, table and takeaway orders from one menu.", description: "Support modifiers, combos, availability and lightweight table service without duplicating menu maintenance.", needs: ["Flexible order modes", "Easy customization", "Simple menu updates"], servora: ["Dine-in and takeaway", "Variants and modifier quantities", "Schedules, availability and bulk editing"] },
  { slug: "full-service", type: "business", name: "Full-service restaurants", eyebrow: "Solutions by restaurant", headline: "Keep multi-round table service connected from guest to bill.", description: "Coordinate waiters, tables, kitchen rounds, service requests and complete-tab settlement.", needs: ["Table context", "Multiple kitchen rounds", "Flexible settlement"], servora: ["QR and waiter-led orders", "Order-more and course-aware progress", "Transfers, splits, merges and billing"] },
  { slug: "buffets", type: "business", name: "Buffets", eyebrow: "Solutions by restaurant", headline: "Use cover-based billing without losing kitchen or inventory detail.", description: "Apply adult or child cover pricing while items still fire to the kitchen and consume inventory.", needs: ["Per-cover rates", "Cover counts", "Operational item tracking"], servora: ["Buffet and per-cover rules", "Customer groups and pricing", "Recipe and inventory consumption"] },
  { slug: "cloud-kitchens", type: "business", name: "Cloud kitchens", eyebrow: "Solutions by restaurant", headline: "Coordinate menus, channels and kitchen stations without a dining room.", description: "Manage takeaway and delivery ordering, channel pricing and station-routed production across brands or branches.", needs: ["Channel control", "Kitchen routing", "Takeaway fulfillment"], servora: ["Channel overrides", "Station-based KDS", "Delivery and paid takeaway orders"] },
  { slug: "restaurant-groups", type: "business", name: "Restaurant groups", eyebrow: "Solutions by restaurant", headline: "Build a repeatable operating model across locations.", description: "Share governance and visibility while branches retain the controls needed for local service.", needs: ["Reusable standards", "Comparable reporting", "Controlled local changes"], servora: ["Templates and bulk menu tools", "Multi-branch analytics", "Branch overrides and permission boundaries"] },
];
export const solutionBySlug = Object.fromEntries(solutions.map((solution) => [solution.slug, solution]));
