import type { KitchenTicket } from "@pos/types";
export const ticket: KitchenTicket = {
  id: "t1",
  tenantId: "tenant1",
  branchId: "branch1",
  orderId: "o1",
  ticketNumber: 1,
  status: "FIRED",
  courseId: null,
  notes: "No onion",
  items: [
    {
      id: "i1",
      orderId: "o1",
      menuItemId: "m1",
      menuItemName: "Burger",
      variantId: "v1",
      variantName: "Large",
      quantity: 2,
      unitPrice: 100,
      subtotal: 200,
      taxRate: 5,
      taxMode: "EXCLUSIVE",
      pricingAttribution: { BASE_PRICE: 100, VARIANT: 0, MODIFIER: 0 },
      stationId: null,
      menuChangeEventId: null,
      itemStatus: "ACTIVE",
      refiresOrderItemId: null,
      refireReason: null,
      refiredBy: null,
      refiredAt: null,
      voidedReason: null,
      voidedBy: null,
      voidedAt: null,
      voidedReasonId: null,
      compedReason: null,
      compedBy: null,
      compedAt: null,
      compedReasonId: null,
      chefNotes: "Extra hot",
      fulfillmentType: "DINE_IN",
      modifiers: [
        {
          modifierId: "mod1",
          modifierGroupName: "Extras",
          name: "Cheese",
          price: 20,
          quantity: 1,
        },
      ],
    },
  ],
  firedAt: new Date(Date.now() - 1000).toISOString(),
  readyAt: null,
  servedAt: null,
  createdAt: "2026-01-01T00:00:00Z",
  updatedAt: "2026-01-01T00:00:00Z",
  order: {
    id: "o1",
    tenantId: "tenant1",
    branchId: "branch1",
    tableId: "table1",
    table: {
      id: "table1",
      tenantId: "tenant1",
      branchId: "branch1",
      name: "12",
      capacity: 4,
      status: "OCCUPIED",
      section: null,
    },
    customerId: null,
    status: "OPEN",
    type: "DINE_IN",
    subtotal: 200,
    taxAmount: 0,
    discountAmount: 0,
    serviceChargeAmount: 0,
    roundingAdjustment: 0,
    totalAmount: 200,
    notes: null,
    items: [],
    statusHistory: [],
    createdAt: "",
    updatedAt: "",
  },
};
