-- Canonical pre-v1 table migration.

CREATE TABLE "permissions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "key" varchar(100) NOT NULL CONSTRAINT "permissions_key_unique" UNIQUE,
  "module" varchar(50) NOT NULL,
  "description" text
);
--> statement-breakpoint

-- Required RBAC permission catalog for a fresh v1 database.
INSERT INTO "permissions" ("key", "module", "description") VALUES
  ('analytics:read','analytics','Read analytics'),
  ('audit:read','audit','Read tenant audit logs'),
  ('auth:read','auth','Read auth data'),
  ('billing:create','billing','Create bills and payments'),
  ('billing:read','billing','Read billing data'),
  ('billing:refund','billing','Process refunds'),
  ('branch:archive','branch','Archive branches'),
  ('branch:create','branch','Create branches'),
  ('branch:read','branch','View branches'),
  ('branch:update','branch','Update branch details'),
  ('inventory:adjust','inventory','Perform inventory adjustments'),
  ('inventory:create','inventory','Create inventory items'),
  ('inventory:read','inventory','Read inventory'),
  ('inventory:update','inventory','Update inventory stock'),
  ('inventory:waste','inventory','Record inventory waste'),
  ('kitchen:read','kitchen','View kitchen queue'),
  ('kitchen:update','kitchen','Update kitchen order status'),
  ('menu:create','menu','Create menu items'),
  ('menu:delete','menu','Delete menu items'),
  ('menu:pricing:write','menu','Create and update menu pricing rules'),
  ('menu:publish','menu','Publish or unpublish menu items'),
  ('menu:read','menu','Read menu items'),
  ('menu:update','menu','Update menu items'),
  ('orders:cancel','orders','Cancel orders'),
  ('orders:comp','orders','Comp order items'),
  ('orders:create','orders','Create orders'),
  ('orders:read','orders','Read orders'),
  ('orders:update','orders','Update orders'),
  ('orders:update_status','orders','Update order status'),
  ('orders:void','orders','Void order items'),
  ('organization:manage','organization','Manage organization-scoped menus, prices, and member tenants'),
  ('permissions:read','permissions','Read the permission catalog'),
  ('roles:archive','roles','Archive custom roles'),
  ('roles:assign_permissions','roles','Assign permissions to custom roles'),
  ('roles:create','roles','Create custom roles'),
  ('roles:read','roles','Read roles and role permissions'),
  ('roles:update','roles','Update custom roles'),
  ('settings:read','settings','Read settings'),
  ('settings:update','settings','Update settings'),
  ('staff:assign_branch','staff','Assign membership branches'),
  ('staff:assign_role','staff','Assign membership roles'),
  ('staff:create','staff','Create staff members'),
  ('staff:deactivate','staff','Deactivate staff members'),
  ('staff:read','staff','Read staff data'),
  ('staff:update','staff','Update staff members'),
  ('tables:create','tables','Create restaurant tables'),
  ('tables:delete','tables','Remove restaurant tables'),
  ('tables:read','tables','View restaurant tables'),
  ('tables:update','tables','Update table details and status'),
  ('tenant:archive','tenant','Archive a tenant'),
  ('tenant:create','tenant','Create a new tenant'),
  ('tenant:manage_members','tenant','Manage tenant membership'),
  ('tenant:read','tenant','Read tenant data'),
  ('tenant:update','tenant','Update tenant settings');
--> statement-breakpoint
