-- Clean baseline indexes.
CREATE INDEX "branches_tenant_idx" ON "branches" USING btree ("tenant_id");
CREATE UNIQUE INDEX "refresh_tokens_token_hash_unique" ON "refresh_tokens" USING btree ("token_hash");
CREATE INDEX "refresh_tokens_user_idx" ON "refresh_tokens" USING btree ("user_id");
CREATE UNIQUE INDEX "users_email_lower_unique" ON "users" USING btree (lower("email")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "tenant_memberships_user_tenant_uniq" ON "tenant_memberships" USING btree ("user_id","tenant_id");
CREATE INDEX "attendance_user_branch_idx" ON "attendance_logs" USING btree ("user_id","branch_id");
CREATE INDEX "staff_shifts_user_idx" ON "staff_shifts" USING btree ("user_id");
CREATE INDEX "tables_tenant_branch_idx" ON "restaurant_tables" USING btree ("tenant_id","branch_id");
CREATE UNIQUE INDEX "holidays_tenant_date_region_unique" ON "holidays" USING btree ("tenant_id","holiday_date","region");
CREATE INDEX "menu_categories_tenant_idx" ON "menu_categories" USING btree ("tenant_id");
CREATE INDEX "menu_item_branch_overrides_branch_idx" ON "menu_item_branch_overrides" USING btree ("tenant_id","branch_id");
CREATE UNIQUE INDEX "menu_item_branch_overrides_item_branch_unique" ON "menu_item_branch_overrides" USING btree ("menu_item_id","branch_id");
CREATE INDEX "menu_schedules_menu_item_idx" ON "menu_item_schedules" USING btree ("menu_item_id");
CREATE INDEX "menu_schedules_branch_idx" ON "menu_item_schedules" USING btree ("branch_id");
CREATE INDEX "menu_schedules_active_idx" ON "menu_item_schedules" USING btree ("is_active");
CREATE INDEX "menu_items_tenant_idx" ON "menu_items" USING btree ("tenant_id");
CREATE INDEX "menu_items_category_idx" ON "menu_items" USING btree ("category_id");
CREATE INDEX "menu_items_status_idx" ON "menu_items" USING btree ("tenant_id","branch_id","status");
CREATE INDEX "menu_template_items_template_idx" ON "menu_template_items" USING btree ("template_id");
CREATE INDEX "menu_templates_tenant_idx" ON "menu_templates" USING btree ("tenant_id");
CREATE INDEX "modifier_groups_tenant_idx" ON "modifier_groups" USING btree ("tenant_id");
CREATE INDEX "recipes_menu_item_idx" ON "recipes" USING btree ("menu_item_id");
CREATE INDEX "recipes_inventory_item_idx" ON "recipes" USING btree ("inventory_item_id");
CREATE UNIQUE INDEX "recipes_menu_item_inventory_item_unique" ON "recipes" USING btree ("menu_item_id","inventory_item_id");
CREATE INDEX "inventory_tenant_branch_idx" ON "inventory_items" USING btree ("tenant_id","branch_id");
CREATE INDEX "inventory_transactions_item_idx" ON "inventory_transactions" USING btree ("inventory_item_id");
CREATE INDEX "order_inventory_deductions_order_idx" ON "order_inventory_deductions" USING btree ("order_id");
CREATE INDEX "order_inventory_deductions_menu_item_idx" ON "order_inventory_deductions" USING btree ("menu_item_id");
CREATE INDEX "orders_tenant_branch_idx" ON "orders" USING btree ("tenant_id","branch_id");
CREATE INDEX "orders_status_idx" ON "orders" USING btree ("status");
CREATE INDEX "orders_created_at_idx" ON "orders" USING btree ("created_at");
CREATE INDEX "kitchen_tickets_tenant_branch_idx" ON "kitchen_tickets" USING btree ("tenant_id","branch_id");
CREATE INDEX "kitchen_tickets_status_idx" ON "kitchen_tickets" USING btree ("status");
CREATE INDEX "kitchen_tickets_order_idx" ON "kitchen_tickets" USING btree ("order_id");
CREATE INDEX "payments_order_idx" ON "payments" USING btree ("order_id");
CREATE INDEX "audit_logs_tenant_idx" ON "audit_logs" USING btree ("tenant_id");
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");
CREATE INDEX "tenant_memberships_user_idx" ON "tenant_memberships" USING btree ("user_id");
CREATE INDEX "tenant_memberships_tenant_idx" ON "tenant_memberships" USING btree ("tenant_id");
CREATE INDEX "membership_roles_membership_idx" ON "membership_roles" USING btree ("membership_id");
CREATE INDEX "membership_roles_role_idx" ON "membership_roles" USING btree ("role_id");
CREATE INDEX "membership_branches_membership_idx" ON "membership_branches" USING btree ("membership_id");
CREATE INDEX "membership_branches_branch_idx" ON "membership_branches" USING btree ("branch_id");
CREATE UNIQUE INDEX "branches_tenant_name_uniq" ON "branches" USING btree ("tenant_id", "name");
CREATE UNIQUE INDEX "role_permissions_role_permission_uniq" ON "role_permissions" USING btree ("role_id", "permission_id");
CREATE UNIQUE INDEX "global_user_roles_user_role_uniq" ON "global_user_roles" USING btree ("user_id", "role_id");

CREATE UNIQUE INDEX "membership_roles_membership_role_uniq" ON "membership_roles" USING btree ("membership_id","role_id");
CREATE UNIQUE INDEX "membership_branches_membership_branch_uniq" ON "membership_branches" USING btree ("membership_id","branch_id");
CREATE INDEX "membership_branches_tenant_idx" ON "membership_branches" USING btree ("tenant_id");
