import React from "react";
import { act, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@pos/ui",()=>({BottomSheet:({open,onClose,title,children}:any)=>open?<div><h2>{title}</h2><button onClick={onClose}>close sheet</button>{children}</div>:null,Button:({children,onClick,...p}:any)=><button onClick={onClick} {...p}>{children}</button>,EmptyState:({title,description}:any)=><div>{title}<span>{description}</span></div>,IconButton:({onClick,...p}:any)=><button onClick={onClick} aria-label={p["aria-label"]}>icon</button>,SearchInput:({value,onChange,onClear,...p}:any)=><div><input value={value} onChange={onChange} aria-label={p["aria-label"]}/><button onClick={onClear}>clear search</button></div>}));
vi.mock("../MenuCard",()=>({MenuCard:({item,onSelect}:any)=><button onClick={()=>onSelect(item)}>card:{item.name}</button>}));
import { CustomerMenuView } from "../CustomerMenuView";
const item=(id:string,categoryId="c1",over:any={})=>({id,name:`Dish ${id}`,description:null,basePrice:"10",pricingMode:"STANDARD",weightUnit:null,imageUrl:null,images:[],categoryId,tagLinks:[],...over} as any);
const combo=(over:any={})=>({id:"co",name:"Combo",description:null,slots:[{id:"s"}],...over} as any);
const baseProps=(over:any={})=>({session:{mode:"DINE_IN",table:"7",area:"Patio",restaurant:"Resto"},placedOrder:false,itemCount:0,total:20,search:"",setSearch:vi.fn(),categories:[{id:"popular",name:"Popular"},{id:"c1",name:"Mains"},{id:"empty",name:"Empty"}],category:"Popular",setCategory:vi.fn(),combos:[],visibleItems:[item("1")],error:null,setError:vi.fn(),onViewOrder:vi.fn(),onCart:vi.fn(),onOpenCombo:vi.fn(),onOpenItem:vi.fn(),...over});
let callbacks:IntersectionObserverCallback[]=[];class IO{constructor(public cb:IntersectionObserverCallback){callbacks.push(cb)}observe(){}disconnect(){}unobserve(){}takeRecords(){return[]}root=null;rootMargin="";thresholds=[]}
beforeEach(()=>{callbacks=[];vi.clearAllMocks();(globalThis as any).IntersectionObserver=IO;window.requestAnimationFrame=(cb:any)=>{cb(0);return 1};(HTMLElement.prototype as any).scrollIntoView=vi.fn()});
describe("CustomerMenuView coverage",()=>{
it("covers primary interactions",()=>{const p=baseProps({placedOrder:true,itemCount:1,error:"oops",combos:[combo(),combo({id:"co2",name:"Described",description:"hello",slots:[]})],visibleItems:[item("1","c1",{imageUrl:"x.jpg",description:"nice"}),item("2")]});render(<CustomerMenuView {...p}/>);fireEvent.click(screen.getByLabelText("View live order status"));fireEvent.change(screen.getByLabelText("Search the menu"),{target:{value:"pi"}});fireEvent.click(screen.getByText("clear search"));fireEvent.click(screen.getByText("Dish 1"));fireEvent.click(screen.getByText("Combo"));expect(screen.getByText("1 guided choices")).toBeTruthy();expect(screen.getByText("hello")).toBeTruthy();fireEvent.click(screen.getByLabelText("Browse menu categories"));fireEvent.click(screen.getByRole("button",{name:/Mains 2 items/}));fireEvent.click(screen.getByText("Dismiss"));fireEvent.click(screen.getByText(/View order/));expect(p.onCart).toHaveBeenCalled();expect(screen.getByText(/1 item/)).toBeTruthy()});
it("covers takeaway tagged popular and pricing",()=>{const tagged=item("p","c1",{pricingMode:"OPEN",images:[{url:"fallback.jpg"}],tagLinks:[{tag:{name:"POPULAR"}}]});const p=baseProps({session:{mode:"TAKEAWAY",table:null,area:"Takeaway",restaurant:"R"},itemCount:2,category:"Mains",visibleItems:[tagged,item("w","c1",{pricingMode:"WEIGHT_BASED",weightUnit:null}),item("s")]});render(<CustomerMenuView {...p}/>);expect(screen.getAllByText("Takeaway").length).toBeGreaterThan(0);expect(screen.getAllByText("Staff priced").length).toBeGreaterThan(0);expect(screen.getByText(/2 items/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Mains"}));callbacks.forEach(cb=>cb([{isIntersecting:true} as any],{} as any));expect(p.setCategory).toHaveBeenCalled()});
it("covers search progressive loading and empty state",()=>{const many=Array.from({length:13},(_,i)=>item(String(i)));const {rerender}=render(<CustomerMenuView {...baseProps({search:"pizza",visibleItems:many,categories:[]})}/>);expect(screen.getByText(/Loading more/)).toBeTruthy();act(()=>{callbacks.forEach(cb=>cb([{isIntersecting:false} as any],{} as any));callbacks.forEach(cb=>cb([{isIntersecting:true} as any],{} as any));});expect(screen.queryByText(/Loading more/)).toBeNull();rerender(<CustomerMenuView {...baseProps({search:"none",visibleItems:[],categories:[]})}/>);expect(screen.getByText("No dishes found")).toBeTruthy()});
it("covers no image and sheet close",()=>{render(<CustomerMenuView {...baseProps()}/>);expect(screen.queryByRole("img")).toBeNull();fireEvent.click(screen.getByLabelText("Browse menu categories"));fireEvent.click(screen.getByText("close sheet"));expect(screen.queryByText("Browse categories")).toBeNull()})});
it("covers featured weight pricing default unit",()=>{const weighted=item("w","c1",{pricingMode:"WEIGHT_BASED",weightUnit:null,tagLinks:[{tag:{name:"popular"}}]});render(<CustomerMenuView {...baseProps({visibleItems:[weighted],combos:[],categories:[{id:"popular",name:"Popular"},{id:"c1",name:"Mains"}]})}/>);expect(screen.getByText(/unit/)).toBeTruthy();});
