import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { ItemCustomization } from "../ItemCustomization";
const option=(over:any={})=>({id:"o1",name:"Cheese",additionalPrice:"1",isAvailable:true,maxQuantity:3,variantPrices:[],...over});
const group=(over:any={})=>({id:"g1",name:"Extras",selectionType:"MULTIPLE",minSelections:0,maxSelections:3,options:[option()],dependsOnOptionId:null,...over});
const item=(over:any={})=>({id:"i1",name:"Pizza",description:"Good",basePrice:"10",pricingMode:"FIXED",weightUnit:null,imageUrl:null,images:[],foodType:"VEG",spiceLevel:"MILD",variants:[],modifierGroupLinks:[{group:group()}],supportsZones:false,displayMode:"STANDARD",...over} as any);
const props=(over:any={})=>({item:item(),selectedOptions:[],variantId:undefined,onVariantChange:vi.fn(),onToggle:vi.fn(),onOptionQuantity:vi.fn(),onClose:vi.fn(),onAdd:vi.fn(),quantity:1,onQuantityChange:vi.fn(),...over});
describe("ItemCustomization exhaustive",()=>{
 it("renders basic item and quantity/add interactions",()=>{const p=props();render(<ItemCustomization {...p}/>);expect(screen.getByText("Pizza")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Increase quantity"}));expect(p.onQuantityChange).toHaveBeenCalledWith(2);expect(screen.getByRole("button",{name:"Decrease quantity"}).hasAttribute("disabled")).toBe(true);fireEvent.click(screen.getByRole("button",{name:/Add to order/}));expect(p.onAdd).toHaveBeenCalled();fireEvent.click(screen.getByText("Cheese"));expect(p.onToggle).toHaveBeenCalledWith("o1","g1",undefined);});
 it("covers variants, unavailable variants, editing, image and food badges",()=>{const p=props({editing:true,variantId:undefined,quantity:2,item:item({imageUrl:"x.jpg",foodType:"EGG",variants:[{id:"v1",name:"Large",price:"12",status:"ACTIVE"},{id:"v2",name:"Off",price:"9",manualOverrideStatus:"INACTIVE"}]})});render(<ItemCustomization {...p}/>);const radios=screen.getAllByRole("radio");fireEvent.click(radios[0]!);expect(p.onVariantChange).toHaveBeenCalledWith("v1");expect((radios[1] as HTMLInputElement).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"Decrease quantity"}));expect(p.onQuantityChange).toHaveBeenCalledWith(1);expect(screen.getByText("Contains egg")).toBeTruthy();expect(screen.getByText(/Update order/)).toBeTruthy();});
 it("covers weight/open pricing and non-veg/no spice",()=>{const {rerender}=render(<ItemCustomization {...props({item:item({pricingMode:"WEIGHT_BASED",weightUnit:"KG",foodType:"NON_VEG",spiceLevel:"NONE",modifierGroupLinks:[]})})}/>);expect(screen.getAllByText(/kg/).length).toBeGreaterThan(0);expect(screen.getByText("Non-vegetarian")).toBeTruthy();rerender(<ItemCustomization {...props({item:item({pricingMode:"OPEN",modifierGroupLinks:[]})})}/>);expect(screen.getAllByText("Staff priced").length).toBeGreaterThan(0);});
 it("covers guided zones, dependent groups, selected multiple quantity and variant price",()=>{const p=props({variantId:"v",selectedOptions:[{optionId:"o1",quantity:1,zoneLabel:"LEFT"}],item:item({supportsZones:true,displayMode:"GUIDED_BUILDER",variants:[{id:"v",name:"Only",price:"11",status:"ACTIVE"}],modifierGroupLinks:[{group:group({minSelections:1,options:[option({variantPrices:[{variantId:"v",additionalPrice:"2"}]})]})},{group:group({id:"dep",name:"Dependent",dependsOnOptionId:"o1",options:[option({id:"o2",name:"Sauce"})]})},{group:group({id:"hidden",name:"Hidden",dependsOnOptionId:"missing"})}]})});render(<ItemCustomization {...p}/>);expect(screen.getByText(/Build your dish/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Right half"}));fireEvent.click(screen.getByRole("button",{name:"Left half"}));fireEvent.click(screen.getByRole("button",{name:"Increase Cheese"}));expect(p.onOptionQuantity).toHaveBeenCalledWith("o1",1,"LEFT");fireEvent.click(screen.getByRole("button",{name:"Decrease Cheese"}));expect(p.onOptionQuantity).toHaveBeenCalledWith("o1",-1,"LEFT");expect(screen.queryByText("Hidden")).toBeNull();expect(screen.getByText(/Dependent/)).toBeTruthy();});
 it("covers validation error/disabled add and optional single group",()=>{const p=props({item:item({variants:[{id:"v",name:"V",price:"10",status:"ACTIVE"}],modifierGroupLinks:[{group:group({selectionType:"SINGLE",minSelections:1,maxSelections:1})}]})});render(<ItemCustomization {...p}/>);const add=screen.getByRole("button",{name:/Add to order/});expect((add as HTMLButtonElement).disabled).toBe(true);expect(screen.getByRole("alert")).toBeTruthy();});
});
